language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - php: 7.1
      env: dependencies="--prefer-lowest"
    - php: 7.3
      env: CHECK_CODESTYLE=1
      before_install: phpenv config-rm xdebug.ini
      before_script:
        - travis_retry wget -q https://github.com/Roave/BackwardCompatibilityCheck/releases/download/2.0.0/roave-backward-compatibility-check.phar -O ./roave-backward-compatibility-check.phar
        - travis_retry yarn add danger
      script:
        - composer analyze
        - if [ `git tag | wc -l` -gt 0 ]; then php ./roave-backward-compatibility-check.phar --format=markdown >bc-changes.md; fi
        - yarn danger ci
      after_success: ~

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction $DEPENDENCIES

script:
  - vendor/bin/phpunit --coverage-clover coverage-clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
